apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-files
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: write
      image: ubuntu
      script: |
        echo "Sample text" > /workspace/shared-workspace/sample.txt
# ---
# apiVersion: tekton.dev/v1
# kind: Task
# metadata:
#   name: prepare-files
# spec:
#   workspaces:
#     - name: shared-workspace
#   steps:
#     - name: write
#       image: python:3.9
#       script: |
#         import os

#         # Define the path to write the file in the workspace
#         output_path = '/workspace/shared-workspace/sample.txt'

#         # Ensure the directory exists
#         os.makedirs(os.path.dirname(output_path), exist_ok=True)

#         # Write "Sample text" to the file
#         with open(output_path, 'w') as f:
#             f.write('Sample text')

#         print(f'File written to {output_path}')
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: consume-files
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: read
      image: ubuntu
      script: |
        cat /workspace/shared-workspace/sample.txt
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: file-sharing-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: prepare
      taskRef:
        name: prepare-files
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: consume
      taskRef:
        name: consume-files
      runAfter:
        - prepare
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: file-sharing-pipeline-run
spec:
  pipelineRef:
    name: file-sharing-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi